export const DATA = [
  {
    id: "'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba'",
    name: 'Đếm ngược năm mới',
    description: '1',
    category: 'string',
    targetDate: new Date('2023-01-01'),
    targetTime: new Date(),
    repeat: 'hàng ngày',
    alarmConfig: 'nhắc đúng giờ',
    theme: '',
    ring: 'alert',
    isPin: true,
    isImportant: true,
    dateCreated: new Date(),
  },
  {
    id: "'bd7acbea-c1b1-46c2-aad53abb28ba'",
    name: 'Đếm ngược năm mới',
    description: '1',
    category: 'string',
    targetDate: new Date('2022-11-10'),
    targetTime: new Date(),
    repeat: 'hàng ngày',
    alarmConfig: 'nhắc đúng giờ',
    theme: '',
    ring: 'alert',
    isPin: false,
    isImportant: true,
    dateCreated: new Date(),
  },
  {
    id: "'bd7acea-c1b1-46c2-aed5-3ad53abb28ba'",
    name: 'Record 1',
    description: '1',
    category: 'string',
    targetDate: new Date('2021-01-01'),
    targetTime: new Date(),
    repeat: 'hàng ngày',
    alarmConfig: 'nhắc đúng giờ',
    theme: '',
    ring: 'alert',
    isImportant: true,
    isPin: false,
    dateCreated: new Date(),
  },
];
