export const DATA = [
  {
    id: "'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba'",
    name: 'Chúc mừng năm mới',
    description: 'Năm mới 2023',
    category: 'Ngày lễ',
    targetDateTime: new Date('2023-01-01').toString(),
    isRepeat: true,
    repeat: 'Hàng ngày',
    isReminder: true,
    reminder: '1',
    color: '#E7F6F2',
    bell: 'string',
    isImportant: false,
    dateCreated: new Date().toString(),
  },
  {
    id: "'bd7acbea-c1b1-46c2-aad53abb28ba'",
    name: 'Đếm ngược năm mới',
    description: '1',
    category: 'string',
    targetDateTime: new Date('2022-11-10'),
    isRepeat: true,
    repeat: 'Hàng ngày',
    isReminder: true,
    reminder: '1',
    color: '#E7F6F2',
    bell: 'string',
    isImportant: false,
    dateCreated: new Date().toString(),
  },
  {
    id: "'bd7acea-c1b1-46c2-aed5-3ad53abb28ba'",
    name: 'Record 1',
    description: '1',
    category: 'string',
    targetDateTime: new Date('2021-01-01'),
    isRepeat: true,
    repeat: 'Hàng ngày',
    isReminder: true,
    reminder: '1',
    color: '#E7F6F2',
    bell: 'string',
    isImportant: false,
    dateCreated: new Date().toString(),
  },
];
